version: '3.7'

services:
  mysql:
    container_name: lamp-mysql
    image: mysql:8-oracle
    volumes:
      - ./db_data:/var/lib/mysql
      - ./mysql/config.cnf:/etc/mysql/my.cnf
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=${DB_NAME:-test_db}
      - MYSQL_USER=${DB_USER:-phper}
      - MYSQL_PASSWORD=${DB_PASS:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-secret}
      - TZ=UTC
    restart: unless-stopped
    ports:    
      - "3306:3306"

  phpmyadmin:
    container_name: lamp-phpmyadmin    
    restart: unless-stopped
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - "8080:80"

  apache:
    container_name: lamp-apache
    restart: unless-stopped
    build:
      context: ./apache
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./htdocs
        target: /var/www/html
      - ./apache/conf/default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./apache/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=lamp-mysql
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME:-test_db}
      - DB_USERNAME=${DB_USER:-phper}
      - DB_PASSWORD=${DB_USER:-secret}

volumes:
    db_data: {}
